import User from "../Models/user.model";

const GROQ_URL =
    "https://api.groq.com/openai/v1/chat/completions";


export const generateGroqResponse = async ({
    prompt,
    apiKey,
    model = "openai/gpt-oss-20b",
    user = null
}) => {

    try {

        // Check API key
        if (!apiKey) {
            throw new Error("Groq API key is missing");
        }

        // Check prompt
        if (!prompt) {
            throw new Error("Prompt is missing");
        }


        const response = await fetch(GROQ_URL, {
            method: "POST",

            headers: {
                "Content-Type": "application/json",
                "Authorization": `Bearer ${apiKey}`
            },

            body: JSON.stringify({
                model,

                messages: [
                    {
                        role: "user",
                        content: prompt
                    }
                ],

                ...(user && { user })
            })
        });


        // Handle API errors
        if (!response.ok) {

            if(response.status === 400 || response.status === 401){

                user.geminiStatus="invalid";

                await user.save();
            }

            if (response.status === 429){
                user.geminiStatus ="quota_exceeded";

                await user.save();
            }


        }

        user.geminiStatus ="active";

        await user.save();
        const data = await response.json();


        const text =
            data?.choices?.[0]?.message?.content;

            console.log(text)


        if (!text) {
            throw new Error("No response generated by Groq");
        }


        return text.trim();

    } catch (error) {

        console.error("Groq Error:", error);

        return {
            success: false,
            error: error.message
        };
    }
};